//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace No8.Ascii.TermInfo;

/// <summary>
///     Terminfo capabilities
/// </summary>
public static class TermInfoCaps
{
    /// <summary>
    ///     boolean terminfo capabilities
    /// </summary>
    public enum Boolean
    {
        /// <summary>
        ///     auto_left_margin [auto_left_margin, bw]: cub 1 wraps from column 0 to last column.
        /// </summary>
        AutoLeftMargin = 0,

        /// <summary>
        ///     auto_right_margin [auto_right_margin, am]: terminal has automatic margins.
        /// </summary>
        AutoRightMargin = 1,

        /// <summary>
        ///     no_esc_ctlc [no_esc_ctlc, xsb]: beehive f 1 escape f 2 ctrl c.
        /// </summary>
        NoEscCtlc = 2,

        /// <summary>
        ///     ceol_standout_glitch [ceol_standout_glitch, xhp]: standout not erased by overwriting hp.
        /// </summary>
        CeolStandoutGlitch = 3,

        /// <summary>
        ///     eat_newline_glitch [eat_newline_glitch, xenl]: newline ignored after 80 cols concept.
        /// </summary>
        EatNewlineGlitch = 4,

        /// <summary>
        ///     erase_overstrike [erase_overstrike, eo]: can erase overstrikes with a blank.
        /// </summary>
        EraseOverstrike = 5,

        /// <summary>
        ///     generic_type [generic_type, gn]: generic line type.
        /// </summary>
        GenericType = 6,

        /// <summary>
        ///     hard_copy [hard_copy, hc]: hardcopy terminal.
        /// </summary>
        HardCopy = 7,

        /// <summary>
        ///     has_meta_key [has_meta_key, km]: has a meta key (i.e., sets 8th bit).
        /// </summary>
        HasMetaKey = 8,

        /// <summary>
        ///     has_status_line [has_status_line, hs]: has extra status line.
        /// </summary>
        HasStatusLine = 9,

        /// <summary>
        ///     insert_null_glitch [insert_null_glitch, in]: insert mode distinguishes nulls.
        /// </summary>
        InsertNullGlitch = 10,

        /// <summary>
        ///     memory_above [memory_above, da]: display may be retained above the screen.
        /// </summary>
        MemoryAbove = 11,

        /// <summary>
        ///     memory_below [memory_below, db]: display may be retained below the screen.
        /// </summary>
        MemoryBelow = 12,

        /// <summary>
        ///     move_insert_mode [move_insert_mode, mir]: safe to move while in insert mode.
        /// </summary>
        MoveInsertMode = 13,

        /// <summary>
        ///     move_standout_mode [move_standout_mode, msgr]: safe to move while in standout mode.
        /// </summary>
        MoveStandoutMode = 14,

        /// <summary>
        ///     over_strike [over_strike, os]: terminal can overstrike.
        /// </summary>
        OverStrike = 15,

        /// <summary>
        ///     status_line_esc_ok [status_line_esc_ok, eslok]: escape can be used on the status line.
        /// </summary>
        StatusLineEscOk = 16,

        /// <summary>
        ///     dest_tabs_magic_smso [dest_tabs_magic_smso, xt]: tabs destructive magic so char t 1061.
        /// </summary>
        DestTabsMagicSmso = 17,

        /// <summary>
        ///     tilde_glitch [tilde_glitch, hz]: cannot print s hazeltine.
        /// </summary>
        TildeGlitch = 18,

        /// <summary>
        ///     transparent_underline [transparent_underline, ul]: underline character overstrikes.
        /// </summary>
        TransparentUnderline = 19,

        /// <summary>
        ///     xon_xoff [xon_xoff, xon]: terminal uses xon xoff handshaking.
        /// </summary>
        XonXoff = 20,

        /// <summary>
        ///     needs_xon_xoff [needs_xon_xoff, nxon]: padding will not work xon xoff required.
        /// </summary>
        NeedsXonXoff = 21,

        /// <summary>
        ///     prtr_silent [prtr_silent, mc5i]: printer will not echo on screen.
        /// </summary>
        PrtrSilent = 22,

        /// <summary>
        ///     hard_cursor [hard_cursor, chts]: cursor is hard to see.
        /// </summary>
        HardCursor = 23,

        /// <summary>
        ///     non_rev_rmcup [non_rev_rmcup, nrrmc]: smcup does not reverse rmcup.
        /// </summary>
        NonRevRmcup = 24,

        /// <summary>
        ///     no_pad_char [no_pad_char, npc]: pad character does not exist.
        /// </summary>
        NoPadChar = 25,

        /// <summary>
        ///     non_dest_scroll_region [non_dest_scroll_region, ndscr]: scrolling region is non destructive.
        /// </summary>
        NonDestScrollRegion = 26,

        /// <summary>
        ///     can_change [can_change, ccc]: terminal can re define existing colors.
        /// </summary>
        CanChange = 27,

        /// <summary>
        ///     back_color_erase [back_color_erase, bce]: screen erased with background color.
        /// </summary>
        BackColorErase = 28,

        /// <summary>
        ///     hue_lightness_saturation [hue_lightness_saturation, hls]: terminal uses only hls color notation tektronix.
        /// </summary>
        HueLightnessSaturation = 29,

        /// <summary>
        ///     col_addr_glitch [col_addr_glitch, xhpa]: only positive motion for hpa mhpa caps.
        /// </summary>
        ColAddrGlitch = 30,

        /// <summary>
        ///     cr_cancels_micro_mode [cr_cancels_micro_mode, crxm]: using cr turns off micro mode.
        /// </summary>
        CrCancelsMicroMode = 31,

        /// <summary>
        ///     has_print_wheel [has_print_wheel, daisy]: printer needs operator to change character set.
        /// </summary>
        HasPrintWheel = 32,

        /// <summary>
        ///     row_addr_glitch [row_addr_glitch, xvpa]: only positive motion for vpa mvpa caps.
        /// </summary>
        RowAddrGlitch = 33,

        /// <summary>
        ///     semi_auto_right_margin [semi_auto_right_margin, sam]: printing in last column causes cr.
        /// </summary>
        SemiAutoRightMargin = 34,

        /// <summary>
        ///     cpi_changes_res [cpi_changes_res, cpix]: changing character pitch changes resolution.
        /// </summary>
        CpiChangesRes = 35,

        /// <summary>
        ///     lpi_changes_res [lpi_changes_res, lpix]: changing line pitch changes resolution.
        /// </summary>
        LpiChangesRes = 36,

        /// <summary>
        ///     backspaces_with_bs [backspaces_with_bs, OTbs]: uses h to move left.
        /// </summary>
        BackspacesWithBs = 37,

        /// <summary>
        ///     crt_no_scrolling [crt_no_scrolling, OTns]: crt cannot scroll.
        /// </summary>
        CrtNoScrolling = 38,

        /// <summary>
        ///     no_correctly_working_cr [no_correctly_working_cr, OTnc]: no way to go to start of line.
        /// </summary>
        NoCorrectlyWorkingCr = 39,

        /// <summary>
        ///     gnu_has_meta_key [gnu_has_meta_key, OTMT]: has meta key.
        /// </summary>
        GnuHasMetaKey = 40,

        /// <summary>
        ///     linefeed_is_newline [linefeed_is_newline, OTNL]: move down with n.
        /// </summary>
        LinefeedIsNewline = 41,

        /// <summary>
        ///     has_hardware_tabs [has_hardware_tabs, OTpt]: has 8 char tabs invoked with ^i.
        /// </summary>
        HasHardwareTabs = 42,

        /// <summary>
        ///     return_does_clr_eol [return_does_clr_eol, OTxr]: return clears the line.
        /// </summary>
        ReturnDoesClrEol = 43,
    }

    /// <summary>
    ///     Numeric terminfo capabilities.
    /// </summary>
    public enum Num
    {
        /// <summary>
        ///     columns [columns, cols]: number of columns in a line.
        /// </summary>
        Columns = 0,

        /// <summary>
        ///     init_tabs [init_tabs, it]: tabs initially every spaces.
        /// </summary>
        InitTabs = 1,

        /// <summary>
        ///     lines [lines, lines]: number of lines on screen or page.
        /// </summary>
        Lines = 2,

        /// <summary>
        ///     lines_of_memory [lines_of_memory, lm]: lines of memory if line 0 means varies.
        /// </summary>
        LinesOfMemory = 3,

        /// <summary>
        ///     magic_cookie_glitch [magic_cookie_glitch, xmc]: number of blank characters left by smso or rmso.
        /// </summary>
        MagicCookieGlitch = 4,

        /// <summary>
        ///     padding_baud_rate [padding_baud_rate, pb]: lowest baud rate where padding needed.
        /// </summary>
        PaddingBaudRate = 5,

        /// <summary>
        ///     virtual_terminal [virtual_terminal, vt]: virtual terminal number cb unix.
        /// </summary>
        VirtualTerminal = 6,

        /// <summary>
        ///     width_status_line [width_status_line, wsl]: number of columns in status line.
        /// </summary>
        WidthStatusLine = 7,

        /// <summary>
        ///     num_labels [num_labels, nlab]: number of labels on screen.
        /// </summary>
        NumLabels = 8,

        /// <summary>
        ///     label_height [label_height, lh]: rows in each label.
        /// </summary>
        LabelHeight = 9,

        /// <summary>
        ///     label_width [label_width, lw]: columns in each label.
        /// </summary>
        LabelWidth = 10,

        /// <summary>
        ///     max_attributes [max_attributes, ma]: maximum combined attributes terminal can handle.
        /// </summary>
        MaxAttributes = 11,

        /// <summary>
        ///     maximum_windows [maximum_windows, wnum]: maximum number of definable windows.
        /// </summary>
        MaximumWindows = 12,

        /// <summary>
        ///     max_colors [max_colors, colors]: maximum number of colors on screen.
        /// </summary>
        MaxColors = 13,

        /// <summary>
        ///     max_pairs [max_pairs, pairs]: maximum number of color pairs on the screen.
        /// </summary>
        MaxPairs = 14,

        /// <summary>
        ///     no_color_video [no_color_video, ncv]: video attributes that cannot be used with colors.
        /// </summary>
        NoColorVideo = 15,

        /// <summary>
        ///     buffer_capacity [buffer_capacity, bufsz]: numbers of bytes buffered before printing.
        /// </summary>
        BufferCapacity = 16,

        /// <summary>
        ///     dot_vert_spacing [dot_vert_spacing, spinv]: spacing of pins vertically in pins per inch.
        /// </summary>
        DotVertSpacing = 17,

        /// <summary>
        ///     dot_horz_spacing [dot_horz_spacing, spinh]: spacing of dots horizontally in dots per inch.
        /// </summary>
        DotHorzSpacing = 18,

        /// <summary>
        ///     max_micro_address [max_micro_address, maddr]: maximum value in micro ... address.
        /// </summary>
        MaxMicroAddress = 19,

        /// <summary>
        ///     max_micro_jump [max_micro_jump, mjump]: maximum value in parm ... micro.
        /// </summary>
        MaxMicroJump = 20,

        /// <summary>
        ///     micro_col_size [micro_col_size, mcs]: character step size when in micro mode.
        /// </summary>
        MicroColSize = 21,

        /// <summary>
        ///     micro_line_size [micro_line_size, mls]: line step size when in micro mode.
        /// </summary>
        MicroLineSize = 22,

        /// <summary>
        ///     number_of_pins [number_of_pins, npins]: numbers of pins in print head.
        /// </summary>
        NumberOfPins = 23,

        /// <summary>
        ///     output_res_char [output_res_char, orc]: horizontal resolution in units per line.
        /// </summary>
        OutputResChar = 24,

        /// <summary>
        ///     output_res_line [output_res_line, orl]: vertical resolution in units per line.
        /// </summary>
        OutputResLine = 25,

        /// <summary>
        ///     output_res_horz_inch [output_res_horz_inch, orhi]: horizontal resolution in units per inch.
        /// </summary>
        OutputResHorzInch = 26,

        /// <summary>
        ///     output_res_vert_inch [output_res_vert_inch, orvi]: vertical resolution in units per inch.
        /// </summary>
        OutputResVertInch = 27,

        /// <summary>
        ///     print_rate [print_rate, cps]: print rate in characters per second.
        /// </summary>
        PrintRate = 28,

        /// <summary>
        ///     wide_char_size [wide_char_size, widcs]: character step size when in double wide mode.
        /// </summary>
        WideCharSize = 29,

        /// <summary>
        ///     buttons [buttons, btns]: number of buttons on mouse.
        /// </summary>
        Buttons = 30,

        /// <summary>
        ///     bit_image_entwining [bit_image_entwining, bitwin]: number of passes for each bit image row.
        /// </summary>
        BitImageEntwining = 31,

        /// <summary>
        ///     bit_image_type [bit_image_type, bitype]: type of bit image device.
        /// </summary>
        BitImageType = 32,

        /// <summary>
        ///     magic_cookie_glitch_ul [magic_cookie_glitch_ul, OTug]: number of blanks left by ul.
        /// </summary>
        MagicCookieGlitchUl = 33,

        /// <summary>
        ///     carriage_return_delay [carriage_return_delay, OTdC]: pad needed for cr.
        /// </summary>
        CarriageReturnDelay = 34,

        /// <summary>
        ///     new_line_delay [new_line_delay, OTdN]: pad needed for lf.
        /// </summary>
        NewLineDelay = 35,

        /// <summary>
        ///     backspace_delay [backspace_delay, OTdB]: padding required for h.
        /// </summary>
        BackspaceDelay = 36,

        /// <summary>
        ///     horizontal_tab_delay [horizontal_tab_delay, OTdT]: padding required for i.
        /// </summary>
        HorizontalTabDelay = 37,

        /// <summary>
        ///     number_of_function_keys [number_of_function_keys, OTkn]: count of function keys.
        /// </summary>
        NumberOfFunctionKeys = 38,
    }

    /// <summary>
    ///     string terminfo capabilities.
    /// </summary>
    public enum String
    {
        /// <summary>
        ///     back_tab [back_tab, cbt]: the back tab p.
        /// </summary>
        BackTab = 0,

        /// <summary>
        ///     bell [bell, bel]: the audible signal bell p.
        /// </summary>
        Bell = 1,

        /// <summary>
        ///     carriage_return [carriage_return, cr]: the carriage return p p.
        /// </summary>
        CarriageReturn = 2,

        /// <summary>
        ///     change_scroll_region [change_scroll_region, csr]: the change region to line 1 to line 2 p.
        /// </summary>
        ChangeScrollRegion = 3,

        /// <summary>
        ///     clear_all_tabs [clear_all_tabs, tbc]: the clear all tab stops p.
        /// </summary>
        ClearAllTabs = 4,

        /// <summary>
        ///     clear_screen [clear_screen, clear]: the clear screen and home cursor p.
        /// </summary>
        ClearScreen = 5,

        /// <summary>
        ///     clr_eol [clr_eol, el]: the clear to end of line p.
        /// </summary>
        ClrEol = 6,

        /// <summary>
        ///     clr_eos [clr_eos, ed]: the clear to end of screen p.
        /// </summary>
        ClrEos = 7,

        /// <summary>
        ///     column_address [column_address, hpa]: the horizontal position 1 absolute p.
        /// </summary>
        ColumnAddress = 8,

        /// <summary>
        ///     command_character [command_character, cmdch]: the terminal settable cmd character in prototype.
        /// </summary>
        CommandCharacter = 9,

        /// <summary>
        ///     cursor_address [cursor_address, cup]: the move to row 1 columns 2.
        /// </summary>
        CursorAddress = 10,

        /// <summary>
        ///     cursor_down [cursor_down, cud1]: the down one line.
        /// </summary>
        CursorDown = 11,

        /// <summary>
        ///     cursor_home [cursor_home, home]: the home cursor if no cup.
        /// </summary>
        CursorHome = 12,

        /// <summary>
        ///     cursor_invisible [cursor_invisible, civis]: the make cursor invisible.
        /// </summary>
        CursorInvisible = 13,

        /// <summary>
        ///     cursor_left [cursor_left, cub1]: the move left one space.
        /// </summary>
        CursorLeft = 14,

        /// <summary>
        ///     cursor_mem_address [cursor_mem_address, mrcup]: the memory relative cursor addressing move to row 1 columns 2.
        /// </summary>
        CursorMemAddress = 15,

        /// <summary>
        ///     cursor_normal [cursor_normal, cnorm]: the make cursor appear normal undo civis cvvis.
        /// </summary>
        CursorNormal = 16,

        /// <summary>
        ///     cursor_right [cursor_right, cuf1]: the non destructive space (move right one space).
        /// </summary>
        CursorRight = 17,

        /// <summary>
        ///     cursor_to_ll [cursor_to_ll, ll]: the last line first column if no cup.
        /// </summary>
        CursorToLl = 18,

        /// <summary>
        ///     cursor_up [cursor_up, cuu1]: the up one line.
        /// </summary>
        CursorUp = 19,

        /// <summary>
        ///     cursor_visible [cursor_visible, cvvis]: the make cursor very visible.
        /// </summary>
        CursorVisible = 20,

        /// <summary>
        ///     delete_character [delete_character, dch1]: the delete character p.
        /// </summary>
        DeleteCharacter = 21,

        /// <summary>
        ///     delete_line [delete_line, dl1]: the delete line p.
        /// </summary>
        DeleteLine = 22,

        /// <summary>
        ///     dis_status_line [dis_status_line, dsl]: the disable status line.
        /// </summary>
        DisStatusLine = 23,

        /// <summary>
        ///     down_half_line [down_half_line, hd]: the half a line down.
        /// </summary>
        DownHalfLine = 24,

        /// <summary>
        ///     enter_alt_charset_mode [enter_alt_charset_mode, smacs]: the start alternate character set p.
        /// </summary>
        EnterAltCharsetMode = 25,

        /// <summary>
        ///     enter_blink_mode [enter_blink_mode, blink]: the turn on blinking.
        /// </summary>
        EnterBlinkMode = 26,

        /// <summary>
        ///     enter_bold_mode [enter_bold_mode, bold]: the turn on bold extra bright mode.
        /// </summary>
        EnterBoldMode = 27,

        /// <summary>
        ///     enter_ca_mode [enter_ca_mode, smcup]: the string to start programs using cup.
        /// </summary>
        EnterCaMode = 28,

        /// <summary>
        ///     enter_delete_mode [enter_delete_mode, smdc]: the enter delete mode.
        /// </summary>
        EnterDeleteMode = 29,

        /// <summary>
        ///     enter_dim_mode [enter_dim_mode, dim]: the turn on half bright mode.
        /// </summary>
        EnterDimMode = 30,

        /// <summary>
        ///     enter_insert_mode [enter_insert_mode, smir]: the enter insert mode.
        /// </summary>
        EnterInsertMode = 31,

        /// <summary>
        ///     enter_secure_mode [enter_secure_mode, invis]: the turn on blank mode characters invisible.
        /// </summary>
        EnterSecureMode = 32,

        /// <summary>
        ///     enter_protected_mode [enter_protected_mode, prot]: the turn on protected mode.
        /// </summary>
        EnterProtectedMode = 33,

        /// <summary>
        ///     enter_reverse_mode [enter_reverse_mode, rev]: the turn on reverse video mode.
        /// </summary>
        EnterReverseMode = 34,

        /// <summary>
        ///     enter_standout_mode [enter_standout_mode, smso]: the begin standout mode.
        /// </summary>
        EnterStandoutMode = 35,

        /// <summary>
        ///     enter_underline_mode [enter_underline_mode, smul]: the begin underline mode.
        /// </summary>
        EnterUnderlineMode = 36,

        /// <summary>
        ///     erase_chars [erase_chars, ech]: the erase 1 characters p.
        /// </summary>
        EraseChars = 37,

        /// <summary>
        ///     exit_alt_charset_mode [exit_alt_charset_mode, rmacs]: the end alternate character set p.
        /// </summary>
        ExitAltCharsetMode = 38,

        /// <summary>
        ///     exit_attribute_mode [exit_attribute_mode, sgr0]: the turn off all attributes.
        /// </summary>
        ExitAttributeMode = 39,

        /// <summary>
        ///     exit_ca_mode [exit_ca_mode, rmcup]: the strings to end programs using cup.
        /// </summary>
        ExitCaMode = 40,

        /// <summary>
        ///     exit_delete_mode [exit_delete_mode, rmdc]: the end delete mode.
        /// </summary>
        ExitDeleteMode = 41,

        /// <summary>
        ///     exit_insert_mode [exit_insert_mode, rmir]: the exit insert mode.
        /// </summary>
        ExitInsertMode = 42,

        /// <summary>
        ///     exit_standout_mode [exit_standout_mode, rmso]: the exit standout mode.
        /// </summary>
        ExitStandoutMode = 43,

        /// <summary>
        ///     exit_underline_mode [exit_underline_mode, rmul]: the exit underline mode.
        /// </summary>
        ExitUnderlineMode = 44,

        /// <summary>
        ///     flash_screen [flash_screen, flash]: the visible bell may not move cursor.
        /// </summary>
        FlashScreen = 45,

        /// <summary>
        ///     form_feed [form_feed, ff]: the hardcopy terminal page eject p.
        /// </summary>
        FormFeed = 46,

        /// <summary>
        ///     from_status_line [from_status_line, fsl]: the return from status line.
        /// </summary>
        FromStatusLine = 47,

        /// <summary>
        ///     init_1string [init_1string, is1]: the initialization string.
        /// </summary>
        Init1string = 48,

        /// <summary>
        ///     init_2string [init_2string, is2]: the initialization string.
        /// </summary>
        Init2string = 49,

        /// <summary>
        ///     init_3string [init_3string, is3]: the initialization string.
        /// </summary>
        Init3string = 50,

        /// <summary>
        ///     init_file [init_file, if]: the name of initialization file.
        /// </summary>
        InitFile = 51,

        /// <summary>
        ///     insert_character [insert_character, ich1]: the insert character p.
        /// </summary>
        InsertCharacter = 52,

        /// <summary>
        ///     insert_line [insert_line, il1]: the insert line p.
        /// </summary>
        InsertLine = 53,

        /// <summary>
        ///     insert_padding [insert_padding, ip]: the insert padding after inserted character.
        /// </summary>
        InsertPadding = 54,

        /// <summary>
        ///     key_backspace [key_backspace, kbs]: the backspace key.
        /// </summary>
        KeyBackspace = 55,

        /// <summary>
        ///     key_catab [key_catab, ktbc]: the clear all tabs key.
        /// </summary>
        KeyCatab = 56,

        /// <summary>
        ///     key_clear [key_clear, kclr]: the clear screen or erase key.
        /// </summary>
        KeyClear = 57,

        /// <summary>
        ///     key_ctab [key_ctab, kctab]: the clear tab key.
        /// </summary>
        KeyCtab = 58,

        /// <summary>
        ///     key_dc [key_dc, kdch1]: the delete character key.
        /// </summary>
        KeyDc = 59,

        /// <summary>
        ///     key_dl [key_dl, kdl1]: the delete line key.
        /// </summary>
        KeyDl = 60,

        /// <summary>
        ///     key_down [key_down, kcud1]: the down arrow key.
        /// </summary>
        KeyDown = 61,

        /// <summary>
        ///     key_eic [key_eic, krmir]: the sent by rmir or smir in insert mode.
        /// </summary>
        KeyEic = 62,

        /// <summary>
        ///     key_eol [key_eol, kel]: the clear to end of line key.
        /// </summary>
        KeyEol = 63,

        /// <summary>
        ///     key_eos [key_eos, ked]: the clear to end of screen key.
        /// </summary>
        KeyEos = 64,

        /// <summary>
        ///     key_f0 [key_f0, kf0]: the f 0 function key.
        /// </summary>
        KeyF0 = 65,

        /// <summary>
        ///     key_f1 [key_f1, kf1]: the f 1 function key.
        /// </summary>
        KeyF1 = 66,

        /// <summary>
        ///     key_f10 [key_f10, kf10]: the f 10 function key.
        /// </summary>
        KeyF10 = 67,

        /// <summary>
        ///     key_f2 [key_f2, kf2]: the f 2 function key.
        /// </summary>
        KeyF2 = 68,

        /// <summary>
        ///     key_f3 [key_f3, kf3]: the f 3 function key.
        /// </summary>
        KeyF3 = 69,

        /// <summary>
        ///     key_f4 [key_f4, kf4]: the f 4 function key.
        /// </summary>
        KeyF4 = 70,

        /// <summary>
        ///     key_f5 [key_f5, kf5]: the f 5 function key.
        /// </summary>
        KeyF5 = 71,

        /// <summary>
        ///     key_f6 [key_f6, kf6]: the f 6 function key.
        /// </summary>
        KeyF6 = 72,

        /// <summary>
        ///     key_f7 [key_f7, kf7]: the f 7 function key.
        /// </summary>
        KeyF7 = 73,

        /// <summary>
        ///     key_f8 [key_f8, kf8]: the f 8 function key.
        /// </summary>
        KeyF8 = 74,

        /// <summary>
        ///     key_f9 [key_f9, kf9]: the f 9 function key.
        /// </summary>
        KeyF9 = 75,

        /// <summary>
        ///     key_home [key_home, khome]: the home key.
        /// </summary>
        KeyHome = 76,

        /// <summary>
        ///     key_ic [key_ic, kich1]: the insert character key.
        /// </summary>
        KeyIc = 77,

        /// <summary>
        ///     key_il [key_il, kil1]: the insert line key.
        /// </summary>
        KeyIl = 78,

        /// <summary>
        ///     key_left [key_left, kcub1]: the left arrow key.
        /// </summary>
        KeyLeft = 79,

        /// <summary>
        ///     key_ll [key_ll, kll]: the lower left key (home down).
        /// </summary>
        KeyLl = 80,

        /// <summary>
        ///     key_npage [key_npage, knp]: the next page key.
        /// </summary>
        KeyNpage = 81,

        /// <summary>
        ///     key_ppage [key_ppage, kpp]: the previous page key.
        /// </summary>
        KeyPpage = 82,

        /// <summary>
        ///     key_right [key_right, kcuf1]: the right arrow key.
        /// </summary>
        KeyRight = 83,

        /// <summary>
        ///     key_sf [key_sf, kind]: the scroll forward key.
        /// </summary>
        KeySf = 84,

        /// <summary>
        ///     key_sr [key_sr, kri]: the scroll backward key.
        /// </summary>
        KeySr = 85,

        /// <summary>
        ///     key_stab [key_stab, khts]: the set tab key.
        /// </summary>
        KeyStab = 86,

        /// <summary>
        ///     key_up [key_up, kcuu1]: the up arrow key.
        /// </summary>
        KeyUp = 87,

        /// <summary>
        ///     keypad_local [keypad_local, rmkx]: the leave 'keyboard transmit' mode.
        /// </summary>
        KeypadLocal = 88,

        /// <summary>
        ///     keypad_xmit [keypad_xmit, smkx]: the enter 'keyboard transmit' mode.
        /// </summary>
        KeypadXmit = 89,

        /// <summary>
        ///     lab_f0 [lab_f0, lf0]: the label on function key f 0 if not f 0.
        /// </summary>
        LabF0 = 90,

        /// <summary>
        ///     lab_f1 [lab_f1, lf1]: the label on function key f 1 if not f 1.
        /// </summary>
        LabF1 = 91,

        /// <summary>
        ///     lab_f10 [lab_f10, lf10]: the label on function key f 10 if not f 10.
        /// </summary>
        LabF10 = 92,

        /// <summary>
        ///     lab_f2 [lab_f2, lf2]: the label on function key f 2 if not f 2.
        /// </summary>
        LabF2 = 93,

        /// <summary>
        ///     lab_f3 [lab_f3, lf3]: the label on function key f 3 if not f 3.
        /// </summary>
        LabF3 = 94,

        /// <summary>
        ///     lab_f4 [lab_f4, lf4]: the label on function key f 4 if not f 4.
        /// </summary>
        LabF4 = 95,

        /// <summary>
        ///     lab_f5 [lab_f5, lf5]: the label on function key f 5 if not f 5.
        /// </summary>
        LabF5 = 96,

        /// <summary>
        ///     lab_f6 [lab_f6, lf6]: the label on function key f 6 if not f 6.
        /// </summary>
        LabF6 = 97,

        /// <summary>
        ///     lab_f7 [lab_f7, lf7]: the label on function key f 7 if not f 7.
        /// </summary>
        LabF7 = 98,

        /// <summary>
        ///     lab_f8 [lab_f8, lf8]: the label on function key f 8 if not f 8.
        /// </summary>
        LabF8 = 99,

        /// <summary>
        ///     lab_f9 [lab_f9, lf9]: the label on function key f 9 if not f 9.
        /// </summary>
        LabF9 = 100,

        /// <summary>
        ///     meta_off [meta_off, rmm]: the turn off meta mode.
        /// </summary>
        MetaOff = 101,

        /// <summary>
        ///     meta_on [meta_on, smm]: the turn on meta mode (8th bit on).
        /// </summary>
        MetaOn = 102,

        /// <summary>
        ///     newline [newline, nel]: the newline behave like cr followed by lf.
        /// </summary>
        Newline = 103,

        /// <summary>
        ///     pad_char [pad_char, pad]: the padding char instead of null.
        /// </summary>
        PadChar = 104,

        /// <summary>
        ///     parm_dch [parm_dch, dch]: the delete 1 characters p.
        /// </summary>
        ParmDch = 105,

        /// <summary>
        ///     parm_delete_line [parm_delete_line, dl]: the delete 1 lines p.
        /// </summary>
        ParmDeleteLine = 106,

        /// <summary>
        ///     parm_down_cursor [parm_down_cursor, cud]: the down 1 lines p.
        /// </summary>
        ParmDownCursor = 107,

        /// <summary>
        ///     parm_ich [parm_ich, ich]: the insert 1 characters p.
        /// </summary>
        ParmIch = 108,

        /// <summary>
        ///     parm_index [parm_index, indn]: the scroll forward 1 lines p.
        /// </summary>
        ParmIndex = 109,

        /// <summary>
        ///     parm_insert_line [parm_insert_line, il]: the insert 1 lines p.
        /// </summary>
        ParmInsertLine = 110,

        /// <summary>
        ///     parm_left_cursor [parm_left_cursor, cub]: the move 1 characters to the left p.
        /// </summary>
        ParmLeftCursor = 111,

        /// <summary>
        ///     parm_right_cursor [parm_right_cursor, cuf]: the move 1 characters to the right p.
        /// </summary>
        ParmRightCursor = 112,

        /// <summary>
        ///     parm_rindex [parm_rindex, rin]: the scroll back 1 lines p.
        /// </summary>
        ParmRindex = 113,

        /// <summary>
        ///     parm_up_cursor [parm_up_cursor, cuu]: the up 1 lines p.
        /// </summary>
        ParmUpCursor = 114,

        /// <summary>
        ///     pkey_key [pkey_key, pfkey]: the program function key 1 to type string 2.
        /// </summary>
        PkeyKey = 115,

        /// <summary>
        ///     pkey_local [pkey_local, pfloc]: the program function key 1 to execute string 2.
        /// </summary>
        PkeyLocal = 116,

        /// <summary>
        ///     pkey_xmit [pkey_xmit, pfx]: the program function key 1 to transmit string 2.
        /// </summary>
        PkeyXmit = 117,

        /// <summary>
        ///     print_screen [print_screen, mc0]: the print contents of screen.
        /// </summary>
        PrintScreen = 118,

        /// <summary>
        ///     prtr_off [prtr_off, mc4]: the turn off printer.
        /// </summary>
        PrtrOff = 119,

        /// <summary>
        ///     prtr_on [prtr_on, mc5]: the turn on printer.
        /// </summary>
        PrtrOn = 120,

        /// <summary>
        ///     repeat_char [repeat_char, rep]: the repeat char 1 2 times p.
        /// </summary>
        RepeatChar = 121,

        /// <summary>
        ///     reset_1string [reset_1string, rs1]: the reset string.
        /// </summary>
        Reset1string = 122,

        /// <summary>
        ///     reset_2string [reset_2string, rs2]: the reset string.
        /// </summary>
        Reset2string = 123,

        /// <summary>
        ///     reset_3string [reset_3string, rs3]: the reset string.
        /// </summary>
        Reset3string = 124,

        /// <summary>
        ///     reset_file [reset_file, rf]: the name of reset file.
        /// </summary>
        ResetFile = 125,

        /// <summary>
        ///     restore_cursor [restore_cursor, rc]: the restore cursor to position of last save cursor.
        /// </summary>
        RestoreCursor = 126,

        /// <summary>
        ///     row_address [row_address, vpa]: the vertical position 1 absolute p.
        /// </summary>
        RowAddress = 127,

        /// <summary>
        ///     save_cursor [save_cursor, sc]: the save current cursor position p.
        /// </summary>
        SaveCursor = 128,

        /// <summary>
        ///     scroll_forward [scroll_forward, ind]: the scroll text up p.
        /// </summary>
        ScrollForward = 129,

        /// <summary>
        ///     scroll_reverse [scroll_reverse, ri]: the scroll text down p.
        /// </summary>
        ScrollReverse = 130,

        /// <summary>
        ///     set_attributes [set_attributes, sgr]: the define video attributes #1 #9 (pg9).
        /// </summary>
        SetAttributes = 131,

        /// <summary>
        ///     set_tab [set_tab, hts]: the set a tab in every row current columns.
        /// </summary>
        SetTab = 132,

        /// <summary>
        ///     set_window [set_window, wind]: the current window is lines #1 #2 cols #3 #4.
        /// </summary>
        SetWindow = 133,

        /// <summary>
        ///     tab [tab, ht]: the tab to next 8 space hardware tab stop.
        /// </summary>
        Tab = 134,

        /// <summary>
        ///     to_status_line [to_status_line, tsl]: the move to status line column 1.
        /// </summary>
        ToStatusLine = 135,

        /// <summary>
        ///     underline_char [underline_char, uc]: the underline char and move past it.
        /// </summary>
        UnderlineChar = 136,

        /// <summary>
        ///     up_half_line [up_half_line, hu]: the half a line up.
        /// </summary>
        UpHalfLine = 137,

        /// <summary>
        ///     init_prog [init_prog, iprog]: the path name of program for initialization.
        /// </summary>
        InitProg = 138,

        /// <summary>
        ///     key_a1 [key_a1, ka1]: the upper left of keypad.
        /// </summary>
        KeyA1 = 139,

        /// <summary>
        ///     key_a3 [key_a3, ka3]: the upper right of keypad.
        /// </summary>
        KeyA3 = 140,

        /// <summary>
        ///     key_b2 [key_b2, kb2]: the center of keypad.
        /// </summary>
        KeyB2 = 141,

        /// <summary>
        ///     key_c1 [key_c1, kc1]: the lower left of keypad.
        /// </summary>
        KeyC1 = 142,

        /// <summary>
        ///     key_c3 [key_c3, kc3]: the lower right of keypad.
        /// </summary>
        KeyC3 = 143,

        /// <summary>
        ///     prtr_non [prtr_non, mc5p]: the turn on printer for 1 bytes.
        /// </summary>
        PrtrNon = 144,

        /// <summary>
        ///     char_padding [char_padding, rmp]: the like ip but when in insert mode.
        /// </summary>
        CharPadding = 145,

        /// <summary>
        ///     acs_chars [acs_chars, acsc]: the graphics charset pairs based on vt 100.
        /// </summary>
        AcsChars = 146,

        /// <summary>
        ///     plab_norm [plab_norm, pln]: the program label 1 to show string 2.
        /// </summary>
        PlabNorm = 147,

        /// <summary>
        ///     key_btab [key_btab, kcbt]: the back tab key.
        /// </summary>
        KeyBtab = 148,

        /// <summary>
        ///     enter_xon_mode [enter_xon_mode, smxon]: the turn on xon xoff handshaking.
        /// </summary>
        EnterXonMode = 149,

        /// <summary>
        ///     exit_xon_mode [exit_xon_mode, rmxon]: the turn off xon xoff handshaking.
        /// </summary>
        ExitXonMode = 150,

        /// <summary>
        ///     enter_am_mode [enter_am_mode, smam]: the turn on automatic margins.
        /// </summary>
        EnterAmMode = 151,

        /// <summary>
        ///     exit_am_mode [exit_am_mode, rmam]: the turn off automatic margins.
        /// </summary>
        ExitAmMode = 152,

        /// <summary>
        ///     xon_character [xon_character, xonc]: the xon character.
        /// </summary>
        XonCharacter = 153,

        /// <summary>
        ///     xoff_character [xoff_character, xoffc]: the xoff character.
        /// </summary>
        XoffCharacter = 154,

        /// <summary>
        ///     ena_acs [ena_acs, enacs]: the enable alternate char set.
        /// </summary>
        EnaAcs = 155,

        /// <summary>
        ///     label_on [label_on, smln]: the turn on soft labels.
        /// </summary>
        LabelOn = 156,

        /// <summary>
        ///     label_off [label_off, rmln]: the turn off soft labels.
        /// </summary>
        LabelOff = 157,

        /// <summary>
        ///     key_beg [key_beg, kbeg]: the begin key.
        /// </summary>
        KeyBeg = 158,

        /// <summary>
        ///     key_cancel [key_cancel, kcan]: the cancel key.
        /// </summary>
        KeyCancel = 159,

        /// <summary>
        ///     key_close [key_close, kclo]: the close key.
        /// </summary>
        KeyClose = 160,

        /// <summary>
        ///     key_command [key_command, kcmd]: the command key.
        /// </summary>
        KeyCommand = 161,

        /// <summary>
        ///     key_copy [key_copy, kcpy]: the copy key.
        /// </summary>
        KeyCopy = 162,

        /// <summary>
        ///     key_create [key_create, kcrt]: the create key.
        /// </summary>
        KeyCreate = 163,

        /// <summary>
        ///     key_end [key_end, kend]: the end key.
        /// </summary>
        KeyEnd = 164,

        /// <summary>
        ///     key_enter [key_enter, kent]: the enter send key.
        /// </summary>
        KeyEnter = 165,

        /// <summary>
        ///     key_exit [key_exit, kext]: the exit key.
        /// </summary>
        KeyExit = 166,

        /// <summary>
        ///     key_find [key_find, kfnd]: the find key.
        /// </summary>
        KeyFind = 167,

        /// <summary>
        ///     key_help [key_help, khlp]: the help key.
        /// </summary>
        KeyHelp = 168,

        /// <summary>
        ///     key_mark [key_mark, kmrk]: the mark key.
        /// </summary>
        KeyMark = 169,

        /// <summary>
        ///     key_message [key_message, kmsg]: the message key.
        /// </summary>
        KeyMessage = 170,

        /// <summary>
        ///     key_move [key_move, kmov]: the move key.
        /// </summary>
        KeyMove = 171,

        /// <summary>
        ///     key_next [key_next, knxt]: the next key.
        /// </summary>
        KeyNext = 172,

        /// <summary>
        ///     key_open [key_open, kopn]: the open key.
        /// </summary>
        KeyOpen = 173,

        /// <summary>
        ///     key_options [key_options, kopt]: the options key.
        /// </summary>
        KeyOptions = 174,

        /// <summary>
        ///     key_previous [key_previous, kprv]: the previous key.
        /// </summary>
        KeyPrevious = 175,

        /// <summary>
        ///     key_print [key_print, kprt]: the print key.
        /// </summary>
        KeyPrint = 176,

        /// <summary>
        ///     key_redo [key_redo, krdo]: the redo key.
        /// </summary>
        KeyRedo = 177,

        /// <summary>
        ///     key_reference [key_reference, kref]: the reference key.
        /// </summary>
        KeyReference = 178,

        /// <summary>
        ///     key_refresh [key_refresh, krfr]: the refresh key.
        /// </summary>
        KeyRefresh = 179,

        /// <summary>
        ///     key_replace [key_replace, krpl]: the replace key.
        /// </summary>
        KeyReplace = 180,

        /// <summary>
        ///     key_restart [key_restart, krst]: the restart key.
        /// </summary>
        KeyRestart = 181,

        /// <summary>
        ///     key_resume [key_resume, kres]: the resume key.
        /// </summary>
        KeyResume = 182,

        /// <summary>
        ///     key_save [key_save, ksav]: the save key.
        /// </summary>
        KeySave = 183,

        /// <summary>
        ///     key_suspend [key_suspend, kspd]: the suspend key.
        /// </summary>
        KeySuspend = 184,

        /// <summary>
        ///     key_undo [key_undo, kund]: the undo key.
        /// </summary>
        KeyUndo = 185,

        /// <summary>
        ///     key_sbeg [key_sbeg, kBEG]: the shifted begin key.
        /// </summary>
        KeySbeg = 186,

        /// <summary>
        ///     key_scancel [key_scancel, kCAN]: the shifted cancel key.
        /// </summary>
        KeyScancel = 187,

        /// <summary>
        ///     key_scommand [key_scommand, kCMD]: the shifted command key.
        /// </summary>
        KeyScommand = 188,

        /// <summary>
        ///     key_scopy [key_scopy, kCPY]: the shifted copy key.
        /// </summary>
        KeyScopy = 189,

        /// <summary>
        ///     key_screate [key_screate, kCRT]: the shifted create key.
        /// </summary>
        KeyScreate = 190,

        /// <summary>
        ///     key_sdc [key_sdc, kDC]: the shifted delete character key.
        /// </summary>
        KeySdc = 191,

        /// <summary>
        ///     key_sdl [key_sdl, kDL]: the shifted delete line key.
        /// </summary>
        KeySdl = 192,

        /// <summary>
        ///     key_select [key_select, kslt]: the select key.
        /// </summary>
        KeySelect = 193,

        /// <summary>
        ///     key_send [key_send, kEND]: the shifted end key.
        /// </summary>
        KeySend = 194,

        /// <summary>
        ///     key_seol [key_seol, kEOL]: the shifted clear to end of line key.
        /// </summary>
        KeySeol = 195,

        /// <summary>
        ///     key_sexit [key_sexit, kEXT]: the shifted exit key.
        /// </summary>
        KeySexit = 196,

        /// <summary>
        ///     key_sfind [key_sfind, kFND]: the shifted find key.
        /// </summary>
        KeySfind = 197,

        /// <summary>
        ///     key_shelp [key_shelp, kHLP]: the shifted help key.
        /// </summary>
        KeyShelp = 198,

        /// <summary>
        ///     key_shome [key_shome, kHOM]: the shifted home key.
        /// </summary>
        KeyShome = 199,

        /// <summary>
        ///     key_sic [key_sic, kIC]: the shifted insert character key.
        /// </summary>
        KeySic = 200,

        /// <summary>
        ///     key_sleft [key_sleft, kLFT]: the shifted left arrow key.
        /// </summary>
        KeySleft = 201,

        /// <summary>
        ///     key_smessage [key_smessage, kMSG]: the shifted message key.
        /// </summary>
        KeySmessage = 202,

        /// <summary>
        ///     key_smove [key_smove, kMOV]: the shifted move key.
        /// </summary>
        KeySmove = 203,

        /// <summary>
        ///     key_snext [key_snext, kNXT]: the shifted next key.
        /// </summary>
        KeySnext = 204,

        /// <summary>
        ///     key_soptions [key_soptions, kOPT]: the shifted options key.
        /// </summary>
        KeySoptions = 205,

        /// <summary>
        ///     key_sprevious [key_sprevious, kPRV]: the shifted previous key.
        /// </summary>
        KeySprevious = 206,

        /// <summary>
        ///     key_sprint [key_sprint, kPRT]: the shifted print key.
        /// </summary>
        KeySprint = 207,

        /// <summary>
        ///     key_sredo [key_sredo, kRDO]: the shifted redo key.
        /// </summary>
        KeySredo = 208,

        /// <summary>
        ///     key_sreplace [key_sreplace, kRPL]: the shifted replace key.
        /// </summary>
        KeySreplace = 209,

        /// <summary>
        ///     key_sright [key_sright, kRIT]: the shifted right arrow key.
        /// </summary>
        KeySright = 210,

        /// <summary>
        ///     key_srsume [key_srsume, kRES]: the shifted resume key.
        /// </summary>
        KeySrsume = 211,

        /// <summary>
        ///     key_ssave [key_ssave, kSAV]: the shifted save key.
        /// </summary>
        KeySsave = 212,

        /// <summary>
        ///     key_ssuspend [key_ssuspend, kSPD]: the shifted suspend key.
        /// </summary>
        KeySsuspend = 213,

        /// <summary>
        ///     key_sundo [key_sundo, kUND]: the shifted undo key.
        /// </summary>
        KeySundo = 214,

        /// <summary>
        ///     req_for_input [req_for_input, rfi]: the send next input char for ptys.
        /// </summary>
        ReqForInput = 215,

        /// <summary>
        ///     key_f11 [key_f11, kf11]: the f 11 function key.
        /// </summary>
        KeyF11 = 216,

        /// <summary>
        ///     key_f12 [key_f12, kf12]: the f 12 function key.
        /// </summary>
        KeyF12 = 217,

        /// <summary>
        ///     key_f13 [key_f13, kf13]: the f 13 function key.
        /// </summary>
        KeyF13 = 218,

        /// <summary>
        ///     key_f14 [key_f14, kf14]: the f 14 function key.
        /// </summary>
        KeyF14 = 219,

        /// <summary>
        ///     key_f15 [key_f15, kf15]: the f 15 function key.
        /// </summary>
        KeyF15 = 220,

        /// <summary>
        ///     key_f16 [key_f16, kf16]: the f 16 function key.
        /// </summary>
        KeyF16 = 221,

        /// <summary>
        ///     key_f17 [key_f17, kf17]: the f 17 function key.
        /// </summary>
        KeyF17 = 222,

        /// <summary>
        ///     key_f18 [key_f18, kf18]: the f 18 function key.
        /// </summary>
        KeyF18 = 223,

        /// <summary>
        ///     key_f19 [key_f19, kf19]: the f 19 function key.
        /// </summary>
        KeyF19 = 224,

        /// <summary>
        ///     key_f20 [key_f20, kf20]: the f 20 function key.
        /// </summary>
        KeyF20 = 225,

        /// <summary>
        ///     key_f21 [key_f21, kf21]: the f 21 function key.
        /// </summary>
        KeyF21 = 226,

        /// <summary>
        ///     key_f22 [key_f22, kf22]: the f 22 function key.
        /// </summary>
        KeyF22 = 227,

        /// <summary>
        ///     key_f23 [key_f23, kf23]: the f 23 function key.
        /// </summary>
        KeyF23 = 228,

        /// <summary>
        ///     key_f24 [key_f24, kf24]: the f 24 function key.
        /// </summary>
        KeyF24 = 229,

        /// <summary>
        ///     key_f25 [key_f25, kf25]: the f 25 function key.
        /// </summary>
        KeyF25 = 230,

        /// <summary>
        ///     key_f26 [key_f26, kf26]: the f 26 function key.
        /// </summary>
        KeyF26 = 231,

        /// <summary>
        ///     key_f27 [key_f27, kf27]: the f 27 function key.
        /// </summary>
        KeyF27 = 232,

        /// <summary>
        ///     key_f28 [key_f28, kf28]: the f 28 function key.
        /// </summary>
        KeyF28 = 233,

        /// <summary>
        ///     key_f29 [key_f29, kf29]: the f 29 function key.
        /// </summary>
        KeyF29 = 234,

        /// <summary>
        ///     key_f30 [key_f30, kf30]: the f 30 function key.
        /// </summary>
        KeyF30 = 235,

        /// <summary>
        ///     key_f31 [key_f31, kf31]: the f 31 function key.
        /// </summary>
        KeyF31 = 236,

        /// <summary>
        ///     key_f32 [key_f32, kf32]: the f 32 function key.
        /// </summary>
        KeyF32 = 237,

        /// <summary>
        ///     key_f33 [key_f33, kf33]: the f 33 function key.
        /// </summary>
        KeyF33 = 238,

        /// <summary>
        ///     key_f34 [key_f34, kf34]: the f 34 function key.
        /// </summary>
        KeyF34 = 239,

        /// <summary>
        ///     key_f35 [key_f35, kf35]: the f 35 function key.
        /// </summary>
        KeyF35 = 240,

        /// <summary>
        ///     key_f36 [key_f36, kf36]: the f 36 function key.
        /// </summary>
        KeyF36 = 241,

        /// <summary>
        ///     key_f37 [key_f37, kf37]: the f 37 function key.
        /// </summary>
        KeyF37 = 242,

        /// <summary>
        ///     key_f38 [key_f38, kf38]: the f 38 function key.
        /// </summary>
        KeyF38 = 243,

        /// <summary>
        ///     key_f39 [key_f39, kf39]: the f 39 function key.
        /// </summary>
        KeyF39 = 244,

        /// <summary>
        ///     key_f40 [key_f40, kf40]: the f 40 function key.
        /// </summary>
        KeyF40 = 245,

        /// <summary>
        ///     key_f41 [key_f41, kf41]: the f 41 function key.
        /// </summary>
        KeyF41 = 246,

        /// <summary>
        ///     key_f42 [key_f42, kf42]: the f 42 function key.
        /// </summary>
        KeyF42 = 247,

        /// <summary>
        ///     key_f43 [key_f43, kf43]: the f 43 function key.
        /// </summary>
        KeyF43 = 248,

        /// <summary>
        ///     key_f44 [key_f44, kf44]: the f 44 function key.
        /// </summary>
        KeyF44 = 249,

        /// <summary>
        ///     key_f45 [key_f45, kf45]: the f 45 function key.
        /// </summary>
        KeyF45 = 250,

        /// <summary>
        ///     key_f46 [key_f46, kf46]: the f 46 function key.
        /// </summary>
        KeyF46 = 251,

        /// <summary>
        ///     key_f47 [key_f47, kf47]: the f 47 function key.
        /// </summary>
        KeyF47 = 252,

        /// <summary>
        ///     key_f48 [key_f48, kf48]: the f 48 function key.
        /// </summary>
        KeyF48 = 253,

        /// <summary>
        ///     key_f49 [key_f49, kf49]: the f 49 function key.
        /// </summary>
        KeyF49 = 254,

        /// <summary>
        ///     key_f50 [key_f50, kf50]: the f 50 function key.
        /// </summary>
        KeyF50 = 255,

        /// <summary>
        ///     key_f51 [key_f51, kf51]: the f 51 function key.
        /// </summary>
        KeyF51 = 256,

        /// <summary>
        ///     key_f52 [key_f52, kf52]: the f 52 function key.
        /// </summary>
        KeyF52 = 257,

        /// <summary>
        ///     key_f53 [key_f53, kf53]: the f 53 function key.
        /// </summary>
        KeyF53 = 258,

        /// <summary>
        ///     key_f54 [key_f54, kf54]: the f 54 function key.
        /// </summary>
        KeyF54 = 259,

        /// <summary>
        ///     key_f55 [key_f55, kf55]: the f 55 function key.
        /// </summary>
        KeyF55 = 260,

        /// <summary>
        ///     key_f56 [key_f56, kf56]: the f 56 function key.
        /// </summary>
        KeyF56 = 261,

        /// <summary>
        ///     key_f57 [key_f57, kf57]: the f 57 function key.
        /// </summary>
        KeyF57 = 262,

        /// <summary>
        ///     key_f58 [key_f58, kf58]: the f 58 function key.
        /// </summary>
        KeyF58 = 263,

        /// <summary>
        ///     key_f59 [key_f59, kf59]: the f 59 function key.
        /// </summary>
        KeyF59 = 264,

        /// <summary>
        ///     key_f60 [key_f60, kf60]: the f 60 function key.
        /// </summary>
        KeyF60 = 265,

        /// <summary>
        ///     key_f61 [key_f61, kf61]: the f 61 function key.
        /// </summary>
        KeyF61 = 266,

        /// <summary>
        ///     key_f62 [key_f62, kf62]: the f 62 function key.
        /// </summary>
        KeyF62 = 267,

        /// <summary>
        ///     key_f63 [key_f63, kf63]: the f 63 function key.
        /// </summary>
        KeyF63 = 268,

        /// <summary>
        ///     clr_bol [clr_bol, el1]: the clear to beginning of line.
        /// </summary>
        ClrBol = 269,

        /// <summary>
        ///     clear_margins [clear_margins, mgc]: the clear right and left soft margins.
        /// </summary>
        ClearMargins = 270,

        /// <summary>
        ///     set_left_margin [set_left_margin, smgl]: the set left soft margin at current column.
        /// </summary>
        SetLeftMargin = 271,

        /// <summary>
        ///     set_right_margin [set_right_margin, smgr]: the set right soft margin at current column.
        /// </summary>
        SetRightMargin = 272,

        /// <summary>
        ///     label_format [label_format, fln]: the label format.
        /// </summary>
        LabelFormat = 273,

        /// <summary>
        ///     set_clock [set_clock, sclk]: the set clock 1 hrs 2 mins 3 secs.
        /// </summary>
        SetClock = 274,

        /// <summary>
        ///     display_clock [display_clock, dclk]: the display clock.
        /// </summary>
        DisplayClock = 275,

        /// <summary>
        ///     remove_clock [remove_clock, rmclk]: the remove clock.
        /// </summary>
        RemoveClock = 276,

        /// <summary>
        ///     create_window [create_window, cwin]: the define a window 1 from 2 3 to 4 5.
        /// </summary>
        CreateWindow = 277,

        /// <summary>
        ///     goto_window [goto_window, wingo]: the go to window 1.
        /// </summary>
        GotoWindow = 278,

        /// <summary>
        ///     hangup [hangup, hup]: the hang up phone.
        /// </summary>
        Hangup = 279,

        /// <summary>
        ///     dial_phone [dial_phone, dial]: the dial number 1.
        /// </summary>
        DialPhone = 280,

        /// <summary>
        ///     quick_dial [quick_dial, qdial]: the dial number 1 without checking.
        /// </summary>
        QuickDial = 281,

        /// <summary>
        ///     tone [tone, tone]: the select touch tone dialing.
        /// </summary>
        Tone = 282,

        /// <summary>
        ///     pulse [pulse, pulse]: the select pulse dialing.
        /// </summary>
        Pulse = 283,

        /// <summary>
        ///     flash_hook [flash_hook, hook]: the flash switch hook.
        /// </summary>
        FlashHook = 284,

        /// <summary>
        ///     fixed_pause [fixed_pause, pause]: the pause for 2 3 seconds.
        /// </summary>
        FixedPause = 285,

        /// <summary>
        ///     wait_tone [wait_tone, wait]: the wait for dial tone.
        /// </summary>
        WaitTone = 286,

        /// <summary>
        ///     user0 [user0, u0]: the user string 0.
        /// </summary>
        User0 = 287,

        /// <summary>
        ///     user1 [user1, u1]: the user string 1.
        /// </summary>
        User1 = 288,

        /// <summary>
        ///     user2 [user2, u2]: the user string 2.
        /// </summary>
        User2 = 289,

        /// <summary>
        ///     user3 [user3, u3]: the user string 3.
        /// </summary>
        User3 = 290,

        /// <summary>
        ///     user4 [user4, u4]: the user string 4.
        /// </summary>
        User4 = 291,

        /// <summary>
        ///     user5 [user5, u5]: the user string 5.
        /// </summary>
        User5 = 292,

        /// <summary>
        ///     user6 [user6, u6]: the user string 6.
        /// </summary>
        User6 = 293,

        /// <summary>
        ///     user7 [user7, u7]: the user string 7.
        /// </summary>
        User7 = 294,

        /// <summary>
        ///     user8 [user8, u8]: the user string 8.
        /// </summary>
        User8 = 295,

        /// <summary>
        ///     user9 [user9, u9]: the user string 9.
        /// </summary>
        User9 = 296,

        /// <summary>
        ///     orig_pair [orig_pair, op]: the set default pair to its original value.
        /// </summary>
        OrigPair = 297,

        /// <summary>
        ///     orig_colors [orig_colors, oc]: the set all color pairs to the original ones.
        /// </summary>
        OrigColors = 298,

        /// <summary>
        ///     initialize_color [initialize_color, initc]: the initialize color 1 to 2 3 4.
        /// </summary>
        InitializeColor = 299,

        /// <summary>
        ///     initialize_pair [initialize_pair, initp]: the initialize color pair 1 to fg 2 3 4 bg 5 6 7.
        /// </summary>
        InitializePair = 300,

        /// <summary>
        ///     set_color_pair [set_color_pair, scp]: the set current color pair to 1.
        /// </summary>
        SetColorPair = 301,

        /// <summary>
        ///     set_foreground [set_foreground, setf]: the set foreground color 1.
        /// </summary>
        SetForeground = 302,

        /// <summary>
        ///     set_background [set_background, setb]: the set background color 1.
        /// </summary>
        SetBackground = 303,

        /// <summary>
        ///     change_char_pitch [change_char_pitch, cpi]: the change number of characters per inch to 1.
        /// </summary>
        ChangeCharPitch = 304,

        /// <summary>
        ///     change_line_pitch [change_line_pitch, lpi]: the change number of lines per inch to 1.
        /// </summary>
        ChangeLinePitch = 305,

        /// <summary>
        ///     change_res_horz [change_res_horz, chr]: the change horizontal resolution to 1.
        /// </summary>
        ChangeResHorz = 306,

        /// <summary>
        ///     change_res_vert [change_res_vert, cvr]: the change vertical resolution to 1.
        /// </summary>
        ChangeResVert = 307,

        /// <summary>
        ///     define_char [define_char, defc]: the define a character 1 2 dots wide descender 3.
        /// </summary>
        DefineChar = 308,

        /// <summary>
        ///     enter_doublewide_mode [enter_doublewide_mode, swidm]: the enter double wide mode.
        /// </summary>
        EnterDoublewideMode = 309,

        /// <summary>
        ///     enter_draft_quality [enter_draft_quality, sdrfq]: the enter draft quality mode.
        /// </summary>
        EnterDraftQuality = 310,

        /// <summary>
        ///     enter_italics_mode [enter_italics_mode, sitm]: the enter italic mode.
        /// </summary>
        EnterItalicsMode = 311,

        /// <summary>
        ///     enter_leftward_mode [enter_leftward_mode, slm]: the start leftward carriage motion.
        /// </summary>
        EnterLeftwardMode = 312,

        /// <summary>
        ///     enter_micro_mode [enter_micro_mode, smicm]: the start micro motion mode.
        /// </summary>
        EnterMicroMode = 313,

        /// <summary>
        ///     enter_near_letter_quality [enter_near_letter_quality, snlq]: the enter nlq mode.
        /// </summary>
        EnterNearLetterQuality = 314,

        /// <summary>
        ///     enter_normal_quality [enter_normal_quality, snrmq]: the enter normal quality mode.
        /// </summary>
        EnterNormalQuality = 315,

        /// <summary>
        ///     enter_shadow_mode [enter_shadow_mode, sshm]: the enter shadow print mode.
        /// </summary>
        EnterShadowMode = 316,

        /// <summary>
        ///     enter_subscript_mode [enter_subscript_mode, ssubm]: the enter subscript mode.
        /// </summary>
        EnterSubscriptMode = 317,

        /// <summary>
        ///     enter_superscript_mode [enter_superscript_mode, ssupm]: the enter superscript mode.
        /// </summary>
        EnterSuperscriptMode = 318,

        /// <summary>
        ///     enter_upward_mode [enter_upward_mode, sum]: the start upward carriage motion.
        /// </summary>
        EnterUpwardMode = 319,

        /// <summary>
        ///     exit_doublewide_mode [exit_doublewide_mode, rwidm]: the end double wide mode.
        /// </summary>
        ExitDoublewideMode = 320,

        /// <summary>
        ///     exit_italics_mode [exit_italics_mode, ritm]: the end italic mode.
        /// </summary>
        ExitItalicsMode = 321,

        /// <summary>
        ///     exit_leftward_mode [exit_leftward_mode, rlm]: the end left motion mode.
        /// </summary>
        ExitLeftwardMode = 322,

        /// <summary>
        ///     exit_micro_mode [exit_micro_mode, rmicm]: the end micro motion mode.
        /// </summary>
        ExitMicroMode = 323,

        /// <summary>
        ///     exit_shadow_mode [exit_shadow_mode, rshm]: the end shadow print mode.
        /// </summary>
        ExitShadowMode = 324,

        /// <summary>
        ///     exit_subscript_mode [exit_subscript_mode, rsubm]: the end subscript mode.
        /// </summary>
        ExitSubscriptMode = 325,

        /// <summary>
        ///     exit_superscript_mode [exit_superscript_mode, rsupm]: the end superscript mode.
        /// </summary>
        ExitSuperscriptMode = 326,

        /// <summary>
        ///     exit_upward_mode [exit_upward_mode, rum]: the end reverse character motion.
        /// </summary>
        ExitUpwardMode = 327,

        /// <summary>
        ///     micro_column_address [micro_column_address, mhpa]: the like column address in micro mode.
        /// </summary>
        MicroColumnAddress = 328,

        /// <summary>
        ///     micro_down [micro_down, mcud1]: the like cursor down in micro mode.
        /// </summary>
        MicroDown = 329,

        /// <summary>
        ///     micro_left [micro_left, mcub1]: the like cursor left in micro mode.
        /// </summary>
        MicroLeft = 330,

        /// <summary>
        ///     micro_right [micro_right, mcuf1]: the like cursor right in micro mode.
        /// </summary>
        MicroRight = 331,

        /// <summary>
        ///     micro_row_address [micro_row_address, mvpa]: the like row address #1 in micro mode.
        /// </summary>
        MicroRowAddress = 332,

        /// <summary>
        ///     micro_up [micro_up, mcuu1]: the like cursor up in micro mode.
        /// </summary>
        MicroUp = 333,

        /// <summary>
        ///     order_of_pins [order_of_pins, porder]: the match software bits to print head pins.
        /// </summary>
        OrderOfPins = 334,

        /// <summary>
        ///     parm_down_micro [parm_down_micro, mcud]: the like parm down cursor in micro mode.
        /// </summary>
        ParmDownMicro = 335,

        /// <summary>
        ///     parm_left_micro [parm_left_micro, mcub]: the like parm left cursor in micro mode.
        /// </summary>
        ParmLeftMicro = 336,

        /// <summary>
        ///     parm_right_micro [parm_right_micro, mcuf]: the like parm right cursor in micro mode.
        /// </summary>
        ParmRightMicro = 337,

        /// <summary>
        ///     parm_up_micro [parm_up_micro, mcuu]: the like parm up cursor in micro mode.
        /// </summary>
        ParmUpMicro = 338,

        /// <summary>
        ///     select_char_set [select_char_set, scs]: the select character set 1.
        /// </summary>
        SelectCharSet = 339,

        /// <summary>
        ///     set_bottom_margin [set_bottom_margin, smgb]: the set bottom margin at current line.
        /// </summary>
        SetBottomMargin = 340,

        /// <summary>
        ///     set_bottom_margin_parm [set_bottom_margin_parm, smgbp]: the set bottom margin at line 1 or if smgtp is not given 2 lines from bottom.
        /// </summary>
        SetBottomMarginParm = 341,

        /// <summary>
        ///     set_left_margin_parm [set_left_margin_parm, smglp]: the set left right margin at column 1.
        /// </summary>
        SetLeftMarginParm = 342,

        /// <summary>
        ///     set_right_margin_parm [set_right_margin_parm, smgrp]: the set right margin at column 1.
        /// </summary>
        SetRightMarginParm = 343,

        /// <summary>
        ///     set_top_margin [set_top_margin, smgt]: the set top margin at current line.
        /// </summary>
        SetTopMargin = 344,

        /// <summary>
        ///     set_top_margin_parm [set_top_margin_parm, smgtp]: the set top bottom margin at row 1.
        /// </summary>
        SetTopMarginParm = 345,

        /// <summary>
        ///     start_bit_image [start_bit_image, sbim]: the start printing bit image graphics.
        /// </summary>
        StartBitImage = 346,

        /// <summary>
        ///     start_char_set_def [start_char_set_def, scsd]: the start character set definition 1 with 2 characters in the set.
        /// </summary>
        StartCharSetDef = 347,

        /// <summary>
        ///     stop_bit_image [stop_bit_image, rbim]: the stop printing bit image graphics.
        /// </summary>
        StopBitImage = 348,

        /// <summary>
        ///     stop_char_set_def [stop_char_set_def, rcsd]: the end definition of character set 1.
        /// </summary>
        StopCharSetDef = 349,

        /// <summary>
        ///     subscript_characters [subscript_characters, subcs]: the list of subscriptable characters.
        /// </summary>
        SubscriptCharacters = 350,

        /// <summary>
        ///     superscript_characters [superscript_characters, supcs]: the list of superscriptable characters.
        /// </summary>
        SuperscriptCharacters = 351,

        /// <summary>
        ///     these_cause_cr [these_cause_cr, docr]: the printing any of these characters causes cr.
        /// </summary>
        TheseCauseCr = 352,

        /// <summary>
        ///     zero_motion [zero_motion, zerom]: the no motion for subsequent character.
        /// </summary>
        ZeroMotion = 353,

        /// <summary>
        ///     char_set_names [char_set_names, csnm]: the produce 1 th item from list of character set names.
        /// </summary>
        CharSetNames = 354,

        /// <summary>
        ///     key_mouse [key_mouse, kmous]: the mouse event has occurred.
        /// </summary>
        KeyMouse = 355,

        /// <summary>
        ///     mouse_info [mouse_info, minfo]: the mouse status information.
        /// </summary>
        MouseInfo = 356,

        /// <summary>
        ///     req_mouse_pos [req_mouse_pos, reqmp]: the request mouse position.
        /// </summary>
        ReqMousePos = 357,

        /// <summary>
        ///     get_mouse [get_mouse, getm]: the curses should get button events parameter 1 not documented.
        /// </summary>
        GetMouse = 358,

        /// <summary>
        ///     set_a_foreground [set_a_foreground, setaf]: the set foreground color to 1 using ansi escape.
        /// </summary>
        SetAForeground = 359,

        /// <summary>
        ///     set_a_background [set_a_background, setab]: the set background color to 1 using ansi escape.
        /// </summary>
        SetABackground = 360,

        /// <summary>
        ///     pkey_plab [pkey_plab, pfxl]: the program function key 1 to type string 2 and show string 3.
        /// </summary>
        PkeyPlab = 361,

        /// <summary>
        ///     device_type [device_type, devt]: the indicate language codeset support.
        /// </summary>
        DeviceType = 362,

        /// <summary>
        ///     code_set_init [code_set_init, csin]: the init sequence for multiple codesets.
        /// </summary>
        CodeSetInit = 363,

        /// <summary>
        ///     set0_des_seq [set0_des_seq, s0ds]: the shift to codeset 0 euc set 0 ascii.
        /// </summary>
        Set0DesSeq = 364,

        /// <summary>
        ///     set1_des_seq [set1_des_seq, s1ds]: the shift to codeset 1.
        /// </summary>
        Set1DesSeq = 365,

        /// <summary>
        ///     set2_des_seq [set2_des_seq, s2ds]: the shift to codeset 2.
        /// </summary>
        Set2DesSeq = 366,

        /// <summary>
        ///     set3_des_seq [set3_des_seq, s3ds]: the shift to codeset 3.
        /// </summary>
        Set3DesSeq = 367,

        /// <summary>
        ///     set_lr_margin [set_lr_margin, smglr]: the set both left and right margins to 1 2 ml is not in bsd termcap.
        /// </summary>
        SetLrMargin = 368,

        /// <summary>
        ///     set_tb_margin [set_tb_margin, smgtb]: the sets both top and bottom margins to 1 2.
        /// </summary>
        SetTbMargin = 369,

        /// <summary>
        ///     bit_image_repeat [bit_image_repeat, birep]: the repeat bit image cell 1 2 times.
        /// </summary>
        BitImageRepeat = 370,

        /// <summary>
        ///     bit_image_newline [bit_image_newline, binel]: the move to next row of the bit image.
        /// </summary>
        BitImageNewline = 371,

        /// <summary>
        ///     bit_image_carriage_return [bit_image_carriage_return, bicr]: the move to beginning of same row.
        /// </summary>
        BitImageCarriageReturn = 372,

        /// <summary>
        ///     color_names [color_names, colornm]: the give name for color 1.
        /// </summary>
        ColorNames = 373,

        /// <summary>
        ///     define_bit_image_region [define_bit_image_region, defbi]: the define rectangular bit image region.
        /// </summary>
        DefineBitImageRegion = 374,

        /// <summary>
        ///     end_bit_image_region [end_bit_image_region, endbi]: the end a bit image region.
        /// </summary>
        EndBitImageRegion = 375,

        /// <summary>
        ///     set_color_band [set_color_band, setcolor]: the change to ribbon color 1.
        /// </summary>
        SetColorBand = 376,

        /// <summary>
        ///     set_page_length [set_page_length, slines]: the set page length to 1 lines.
        /// </summary>
        SetPageLength = 377,

        /// <summary>
        ///     display_pc_char [display_pc_char, dispc]: the display pc character 1.
        /// </summary>
        DisplayPcChar = 378,

        /// <summary>
        ///     enter_pc_charset_mode [enter_pc_charset_mode, smpch]: the enter pc character display mode.
        /// </summary>
        EnterPcCharsetMode = 379,

        /// <summary>
        ///     exit_pc_charset_mode [exit_pc_charset_mode, rmpch]: the exit pc character display mode.
        /// </summary>
        ExitPcCharsetMode = 380,

        /// <summary>
        ///     enter_scancode_mode [enter_scancode_mode, smsc]: the enter pc scancode mode.
        /// </summary>
        EnterScancodeMode = 381,

        /// <summary>
        ///     exit_scancode_mode [exit_scancode_mode, rmsc]: the exit pc scancode mode.
        /// </summary>
        ExitScancodeMode = 382,

        /// <summary>
        ///     pc_term_options [pc_term_options, pctrm]: the pc terminal options.
        /// </summary>
        PcTermOptions = 383,

        /// <summary>
        ///     scancode_escape [scancode_escape, scesc]: the escape for scancode emulation.
        /// </summary>
        ScancodeEscape = 384,

        /// <summary>
        ///     alt_scancode_esc [alt_scancode_esc, scesa]: the alternate escape for scancode emulation.
        /// </summary>
        AltScancodeEsc = 385,

        /// <summary>
        ///     enter_horizontal_hl_mode [enter_horizontal_hl_mode, ehhlm]: the enter horizontal highlight mode.
        /// </summary>
        EnterHorizontalHlMode = 386,

        /// <summary>
        ///     enter_left_hl_mode [enter_left_hl_mode, elhlm]: the enter left highlight mode.
        /// </summary>
        EnterLeftHlMode = 387,

        /// <summary>
        ///     enter_low_hl_mode [enter_low_hl_mode, elohlm]: the enter low highlight mode.
        /// </summary>
        EnterLowHlMode = 388,

        /// <summary>
        ///     enter_right_hl_mode [enter_right_hl_mode, erhlm]: the enter right highlight mode.
        /// </summary>
        EnterRightHlMode = 389,

        /// <summary>
        ///     enter_top_hl_mode [enter_top_hl_mode, ethlm]: the enter top highlight mode.
        /// </summary>
        EnterTopHlMode = 390,

        /// <summary>
        ///     enter_vertical_hl_mode [enter_vertical_hl_mode, evhlm]: the enter vertical highlight mode.
        /// </summary>
        EnterVerticalHlMode = 391,

        /// <summary>
        ///     set_a_attributes [set_a_attributes, sgr1]: the define second set of video attributes #1 #6.
        /// </summary>
        SetAAttributes = 392,

        /// <summary>
        ///     set_pglen_inch [set_pglen_inch, slength]: the set page length to 1 hundredth of an inch some implementations use s l for termcap.
        /// </summary>
        SetPglenInch = 393,

        /// <summary>
        ///     termcap_init2 [termcap_init2, OTi2]: the secondary initialization string.
        /// </summary>
        TermcapInit2 = 394,

        /// <summary>
        ///     termcap_reset [termcap_reset, OTrs]: the terminal reset string.
        /// </summary>
        TermcapReset = 395,

        /// <summary>
        ///     linefeed_if_not_lf [linefeed_if_not_lf, OTnl]: the use to move down.
        /// </summary>
        LinefeedIfNotLf = 396,

        /// <summary>
        ///     backspace_if_not_bs [backspace_if_not_bs, OTbc]: the move left if not h.
        /// </summary>
        BackspaceIfNotBs = 397,

        /// <summary>
        ///     other_non_function_keys [other_non_function_keys, OTko]: the list of self mapped keycaps.
        /// </summary>
        OtherNonFunctionKeys = 398,

        /// <summary>
        ///     arrow_key_map [arrow_key_map, OTma]: the map motion keys for vi version 2.
        /// </summary>
        ArrowKeyMap = 399,

        /// <summary>
        ///     acs_ulcorner [acs_ulcorner, OTG2]: the single upper left.
        /// </summary>
        AcsUlcorner = 400,

        /// <summary>
        ///     acs_llcorner [acs_llcorner, OTG3]: the single lower left.
        /// </summary>
        AcsLlcorner = 401,

        /// <summary>
        ///     acs_urcorner [acs_urcorner, OTG1]: the single upper right.
        /// </summary>
        AcsUrcorner = 402,

        /// <summary>
        ///     acs_lrcorner [acs_lrcorner, OTG4]: the single lower right.
        /// </summary>
        AcsLrcorner = 403,

        /// <summary>
        ///     acs_ltee [acs_ltee, OTGR]: the tee pointing right.
        /// </summary>
        AcsLtee = 404,

        /// <summary>
        ///     acs_rtee [acs_rtee, OTGL]: the tee pointing left.
        /// </summary>
        AcsRtee = 405,

        /// <summary>
        ///     acs_btee [acs_btee, OTGU]: the tee pointing up.
        /// </summary>
        AcsBtee = 406,

        /// <summary>
        ///     acs_ttee [acs_ttee, OTGD]: the tee pointing down.
        /// </summary>
        AcsTtee = 407,

        /// <summary>
        ///     acs_hline [acs_hline, OTGH]: the single horizontal line.
        /// </summary>
        AcsHline = 408,

        /// <summary>
        ///     acs_vline [acs_vline, OTGV]: the single vertical line.
        /// </summary>
        AcsVline = 409,

        /// <summary>
        ///     acs_plus [acs_plus, OTGC]: the single intersection.
        /// </summary>
        AcsPlus = 410,

        /// <summary>
        ///     memory_lock [memory_lock, meml]: the lock memory above cursor.
        /// </summary>
        MemoryLock = 411,

        /// <summary>
        ///     memory_unlock [memory_unlock, memu]: the unlock memory.
        /// </summary>
        MemoryUnlock = 412,

        /// <summary>
        ///     box_chars_1 [box_chars_1, box1]: the box characters primary set.
        /// </summary>
        BoxChars1 = 413,
    }
}